### ISSUE TITLE
Unable to activate Jit.ndi on Intel iMac Pro

### ISSUE THREAD

**Issue by randallpacker** [impsnldavid/jit.ndi#24]
I successfully installed jit.ndi v3.0 on an M1 Mac running Max natively, but am unable to do so on my 2017 Intel iMac Pro. Both using the same version of jit.ndi and Big Sur. Whereas jit.ndi on the M1 downloads and installs the runtime successfully, the Intel won't download, forcing me to install the same runtime downloaded on the M1 machine. The externals won't activate on the iMac Pro Intel. Any suggestions?

**Comment by pixsperdavid** [comment]
The exact version and compatibility of the runtime provided from the link is entirely the business of NewTek (the link is to their site and is sourced from their SDK headers). Historically they've been really bad about keeping these links valid and up to date. NDI runtime install problems are out of the scope of this project, however I would suggest if you're having problems that you uninstall everything NDI related, go download the latest NDI tools and install the runtime that way.

**Comment by randallpacker** [comment]
I am confused: if jit.ndi depends on the successful installation of the runtime, how can it be out of the scope of the project? Sounds like you just don't want to deal with it. 

I don't have any problem with NDISyphon, or any other NDI applications. So how is jit.ndi different in terms of its dependency on the runtime? I did reinstall NDI tools 5, so I don't believe that is the problem. It's really a shame because my work with Max makes extensive of NDI. I guess I'll have to use NDISyphon until all this gets resolved. 

Personally, I would suggest you welcome comments and community open source engagement by not closing off a thread immediately, to give others a chance to weigh in. Most Git forums I use give more time and politely ask if they can close it off. 

I'll take this issue to the Max forums and see if others are having similar problems.

**Comment by pixsperdavid** [comment]
It's out of scope because this is an issue tracker for jit.ndi. Open issues on this tracker are designed to represent problems and requests with jit.ndi, not issues with NDI as a whole. Your issue is not with jit.ndi, it is with the NDI runtime. There is nothing I can change in jit.ndi which will help this. I have provided you the best advice I can, which is to install the runtime from the NDI tools rather than the link provided via Max. How else would you suggest that I 'deal with it'?

In terms of community engagement, I don't lock issues. People are free to browse to this issue and continue to discuss it. However I've closed it because currently no action can be taken as a result of it. If you or anyone else feels that there is something which can be done, you/they are free to re-open it.

Also please reconsider your tone of entitlement. This is a free, open-source project which I provide and support at no benefit to myself.
